apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    createdBy: faraz_jahangir
    learning: Kuburnetes
  annotations:
    learning: laerning kuburnetes to pass CKAD
spec:
  containers:
    - name: container-1
      image: nginx
      ports:
        - containerPort: 80